// Mocks generated by Mockito 5.0.0 from annotations
// in learning_app/test/application/login/login_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:learning_app/domain/core/error/failures.dart' as _i5;
import 'package:learning_app/domain/entities/auth_user.dart' as _i6;
import 'package:learning_app/domain/repositories/user/user_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.AuthUser>> authenticate(
          String? email, String? password) =>
      (super.noSuchMethod(Invocation.method(#authenticate, [email, password]),
              returnValue:
                  Future.value(_FakeEither<_i5.Failure, _i6.AuthUser>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.AuthUser>>);
}
